services:
    app:
        profiles: ["disabled"]

    mysql:
        command: --max_allowed_packet=1073741824
        ports:
            - "3306:3306"

    #For development only
    mailpit:
        image: axllent/mailpit
        labels:
            com.symfony.server.service-prefix: 'MAILER'
        ports:
            - "1025:1025"
            - "8025:8025"
